version: 1.0.{build}

branches:
  only:
    - master

os: Visual Studio 2015

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

build_script:
    - msbuild win32-camera-tools.sln /p:Platform=x86
